name: dart_hackathon
description: hackathon project
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0-188.0.dev

# Add regular dependencies here.
dependencies:
math_expressions: ^2.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
